config:
  dockerfile: .woloxci/Dockerfile
  project_name: micro-login-service

services:
  - postgresql
  - redis

steps:
  # analysis:
  #   - bundle exec rubocop -R app spec --format simple
  #   - bundle exec rubycritic --path ./analysis --minimum-score 80 --no-browser
  setup_db:
    - bundle exec rails db:create
    - bundle exec rails db:schema:load
  test:
    - bundle exec rspec
  # security:
  #   - bundle exec brakeman --exit-on-error
  # audit:
  #   - bundle audit check --update


environment:
  POSTGRES_USER: 'postgres'
  POSTGRES_PASSWORD: 'Z0mbie@home'
  POSTGRES_HOST: 'localhost'
  POSTGRES_DB: 'micro_login_db'
  POSTGRES_TEST_DB: 'micro_login_test'
  GMAIL_USERNAME: 'email'
  GMAIL_PASSWORD: 'password'
  GOOGLE_CLIENT_ID: '919453925101-66ul7budqctboi5vf0meu115eismcveu.apps.googleusercontent.com'
  GOOGLE_CLIENT_SECRET: '9Axs5wHG-g_CKOna-XTrFw2h'
  DOMAIN: 'http://localhost:3000'
  RAILS_ENV: ''
  LANG: C.UTF-8